### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by DanielMocanovici** [grammarware/software-evolution#12]
Me and my team has encountered a small (big) issue regarding the project and were wondering if could help us with it. Currently, we sent an email to your teacher email (from my email: d.mocanu@student.utwente.nl), however if you are unable to check your emails, let me know where I could reach you with the question we are having.

**Comment by grammarware** [comment]
![image](https://github.com/grammarware/software-evolution/assets/1658264/cb732a30-b13d-4f53-8bb2-fb3c5e2a9e5e)
